name: Python Game CI

# Trigger the workflow on pushes to the main branch or when a pull request is opened
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version, e.g., 3.8

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame

      # Step 4: Run the game (Optional)
      # You can run the game as a test to ensure everything is set up correctly
      - name: Run the game (Optional)
        run: |
          python main.py
